## SQL Generated by JPA

alter table avsportal.portal_user drop constraint FK9yxgovm8ungyx1iptt72j0b80
       
drop table if exists avsportal.portal_user cascade

create table avsportal.portal_user (
	id uuid not null,
	email varchar(255) not null,
	last_login_on timestamp,
	password varchar(255) not null,
	phone int8 not null,
	role varchar(255),
	updated_on date,
	referred_by uuid,
	
	primary key (id)
)

alter table avsportal.portal_user 
	add constraint FK9yxgovm8ungyx1iptt72j0b80 
			foreign key (referred_by) 
				references avsportal.portal_user


